/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicLayout: typeof import('./src/components/layouts/BasicLayout.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./src/components/pages/SearchPage.vue')['default']
    SearchResultPage: typeof import('./src/components/pages/SearchResultPage.vue')['default']
    TeamPage: typeof import('./src/components/pages/TeamPage.vue')['default']
    UserCardList: typeof import('./src/components/UserCardList.vue')['default']
    UserEditPage: typeof import('./src/components/pages/UserEditPage.vue')['default']
    UserLoginPage: typeof import('./src/components/pages/UserLoginPage.vue')['default']
    UserPage: typeof import('./src/components/pages/UserPage.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
